name: flutter_html_sandbox
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0-alpha.3
  flutter_html_iframe: ^3.0.0-alpha.3
  social_embed_webview: ^0.3.2
  html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true